# Parameter for naming 
nama_prov_archieve = {'NTT' : 'PROVINSI NUSA TENGGARA TIMUR',
                  'NTB' : 'PROVINSI NUSA TENGGARA BARAT',
                  'Bali' : 'PROVINSI BALI' ,
                  'Malut' : 'PROVINSI MALUKU UTARA',
                  'Maluku' : 'PROVINSI MALUKU',
                  'Kepri': 'PROVINSI KEPULAUAN RIAU',
                  'Babel' : 'PROVINSI KEPUALAUN BANGKA BELITUNG',
                  'NAD' : 'PROVINSI NANGGROE ACEH DARUSSALAM',
                  'Sumut' : 'PROVINSI SUMATERA UTARA',
                  'Sumbar' : 'PROVINSI SUMATERA BARAT',
                  'Riau' : 'PROVINSI RIAU',
                  'Jambi' : 'PROVINSI JAMBI',
                  'Sumsel' :  'PROVINSI SUMATERA SELATAN',
                  'Bengkulu' :  'PROVINSI BENGKULU',
                  'Lampung' :  'PROVINSI LAMPUNG',
                  'Banten' :  'PROVINSI BANTEN',
                  'DKI' :  'PROVINSI DKI JAKARTA',
                  'Jabar' :  'PROVINSI JAWA BARAT',
                  'Jateng' : 'PROVINSI JAWA TENGAH',
                  'DIY' :  'PROVINSI DI YOGYAKARTA',
                  'Jatim' : 'PROVINSI JAWA TIMUR',
                  'Kalbar' : 'PROVINSI KALIMANTAN BARAT',
                  'Kalsel' : 'PROVINSI KALIMANTAN SELATAN',
                  'Kalteng' : 'PROVINSI KALIMANTAN TENGAH',
                  'Kaltim' : 'PROVINSI KALIMANTAN TIMUR',
                  'Kaltara' : 'PROVINSI KALIMANTAN UTARA',
                  'Sulbar'  : 'PROVINSI SULAWESI BARAT',
                  'Sulsel'  :  'PROVINSI SULAWESI SELATAN',
                  'Sulteng'  :  'PROVINSI SULAWESI TENGAH',
                  'Sultra'  : 'PROVINSI SULAWESI TENGGARA',
                  'Sulut'  :   'PROVINSI SULAWESI UTARA',
                  'Gorontalo'  : 'PROVINSI GORONTALO',
                  'Papua'  : 'PROVINSI PAPUA',
                  'Papbar'  : 'PROVINSI PAPUA BARAT',
                  'Papsel'  : 'PROVINSI PAPUA SELATAN',
                  'Papteng'  :'PROVINSI PAPUA TENGAH',
                  'Papgun'  : 'PROVINSI PAPUA PEGUNUNGAN',
                  'Papbarda'  : 'PROVINSI PAPUA BARAT DAYA'
                  
            }