# Parameter for naming 
nama_stasiun = {'NTT' : 'STASIUN KLIMATOLOGI NUSA TENGGARA TIMUR',
                  'NTB' : 'STASIUN KLIMATOLOGI NUSA TENGGARA BARAT',
                  'Bali' : 'STASIUN KLIMATOLOGI BALI' ,
                  'Malut' : 'STASIUN METEOROLOGI SULTAN BABULLAH',
                  'Maluku' : 'STASIUN KLIMATOLOGI MALUKU',
                  'Kepri': 'STASIUN METEOROLOGI RAJA HAJI FISABILILLAH TANJUNGPINANG',
                  'Babel' : 'STASIUN KLIMATOLOGI BANGKA BELITUNG',
                  'NAD' : 'STASIUN KLIMATOLOGI ACEH',
                  'Sumut' : 'STASIUN KLIMATOLOGI SUMATERA UTARA',
                  'Sumbar' : 'STASIUN KLIMATOLOGI SUMATERA BARAT',
                  'Riau' : 'STASIUN KLIMATOLOGI RIAU',
                  'Jambi' : 'STASIUN KLIMATOLOGI JAMBI',
                  'Sumsel' :  'PROVINSI SUMATERA SELATAN',
                  'Bengkulu' :  'STASIUN KLIMATOLOGI BENGKULU',
                  'Lampung' :  'STASIUN KLIMATOLOGI LAMPUNG',
                  'Banten' :  'STASIUN KLIMATOLOGI BANTEN',
                  'DKI' :  'STASIUN KLIMATOLOGI BANTEN',
                  'Jabar' :  'STASIUN KLIMATOLOGI JAWA BARAT',
                  'Jateng' : 'STASIUN KLIMATOLOGI JAWA TENGAH',
                  'DIY' :  'STASIUN KLIMATOLOGI D.I YOGYAKARTA',
                  'Jatim' : 'STASIUN KLIMATOLOGI JAWA TIMUR',
                  'Kalbar' : 'STASIUN KLIMATOLOGI KALIMANTAN BARAT',
                  'Kalsel' : 'STASIUN KLIMATOLOGI KALIMANTAN SELATAN',
                  'Kalteng' : 'STASIUN METEOROLOGI TJILIK RIWUT',
                  'Kaltim' : 'STASIUN METEOROLOGI AJI PANGERAN TUMENGGUNG PRANOTO',
                  'Kaltara' : 'STASIUN METEOROLOGI TANJUNG HARAPAN',
                  'Sulbar'  : 'STASIUN METEOROLOGI TAMPA PADANG',
                  'Sulsel'  :  'STASIUN KLIMATOLOGI SULAWESI SELATAN',
                  'Sulteng'  :  'STASIUN PEMANTAU ATMOSFER GLOBAL LORE LINDU BARIRI',
                  'Sultra'  : 'STASIUN KLIMATOLOGI SULAWESI TENGGARA',
                  'Sulut'  :   'STASIUN KLIMATOLOGI SULAWESI UTARA',
                  'Gorontalo'  : 'STASIUN KLIMATOLOGI GORONTALO',
                  'Papua'  : 'STASIUN KLIMATOLOGI JAYAPURA',
                  'Papbar'  : 'STASIUN KLIMATOLOGI PAPUA BARAT',
                  'Papsel'  : 'STASIUN KLIMATOLOGI MERAUKE',
                  'Papteng'  :'STASIUN KLIMATOLOGI JAYAPURA',
                  'Papgun'  : 'STASIUN KLIMATOLOGI MERAUKE',
                  'Papbarda'  : 'STASIUN KLIMATOLOGI PAPUA BARAT'
                  
            }