# Parameter for naming 
nama_prov_folder = {'NTT' : 'PROVINSI_NUSA_TENGGARA_TIMUR',
                  'NTB' : 'PROVINSI_NUSA_TENGGARA_BARAT',
                  'Bali' : 'PROVINSI_BALI' ,
                  'Malut' : 'PROVINSI_MALUKU_UTARA',
                  'Maluku' : 'PROVINSI_MALUKU',
                  'Kepri': 'PROVINSI_KEPULAUAN_RIAU',
                  'Babel' : 'PROVINSI_KEPULAUAN_BANGKA_BELITUNG',
                  'NAD' : 'PROVINSI_NANGGROE_ACEH_DARUSSALAM',
                  'Sumut' : 'PROVINSI_SUMATERA_UTARA',
                  'Sumbar' : 'PROVINSI_SUMATERA_BARAT',
                  'Riau' : 'PROVINSI_RIAU',
                  'Jambi' : 'PROVINSI_JAMBI',
                  'Sumsel' :  'PROVINSI_SUMATERA_SELATAN',
                  'Bengkulu' :  'PROVINSI_BENGKULU',
                  'Lampung' :  'PROVINSI_LAMPUNG',
                  'Banten' :  'PROVINSI_BANTEN',
                  'DKI' :  'PROVINSI_DKI_JAKARTA',
                  'Jabar' :  'PROVINSI_JAWA_BARAT',
                  'Jateng' : 'PROVINSI_JAWA_TENGAH',
                  'DIY' :  'PROVINSI_DI_YOGYAKARTA',
                  'Jatim' : 'PROVINSI_JAWA_TIMUR',
                  'Kalbar' : 'PROVINSI_KALIMANTAN_BARAT',
                  'Kalsel' : 'PROVINSI_KALIMANTAN_SELATAN',
                  'Kalteng' : 'PROVINSI_KALIMANTAN_TENGAH',
                  'Kaltim' : 'PROVINSI_KALIMANTAN_TIMUR',
                  'Kaltara' : 'PROVINSI_KALIMANTAN_UTARA',
                  'Sulbar'  : 'PROVINSI_SULAWESI_BARAT',
                  'Sulsel'  :  'PROVINSI_SULAWESI_SELATAN',
                  'Sulteng'  :  'PROVINSI_SULAWESI_TENGAH',
                  'Sultra'  : 'PROVINSI_SULAWESI_TENGGARA',
                  'Sulut'  :   'PROVINSI_SULAWESI_UTARA',
                  'Gorontalo'  : 'PROVINSI_GORONTALO',
                  'Papua'  : 'PROVINSI_PAPUA',
                  'Papbar'  : 'PROVINSI_PAPUA_BARAT',
                  'Papsel'  : 'PROVINSI_PAPUA_SELATAN',
                  'Papteng'  :'PROVINSI_PAPUA_TENGAH',
                  'Papgun'  : 'PROVINSI_PAPUA_PEGUNUNGAN',
                  'Papbarda'  : 'PROVINSI_PAPUA_BARAT_DAYA'
                  
            }