# Parameter for naming 
nama_prov_union_shp = {'NTT' : 'NUSA TENGGARA TIMUR',
                  'NTB' : 'NUSA TENGGARA BARAT',
                  'Bali' : 'BALI' ,
                  'Malut' : 'MALUKU UTARA',
                  'Maluku' : 'MALUKU',
                  'Kepri': 'KEPULAUAN RIAU',
                  'Babel' : 'KEPULAUAN BANGKA BELITUNG',
                  'NAD' : 'ACEH',
                  'Sumut' : 'SUMATERA UTARA',
                  'Sumbar' : 'SUMATERA BARAT',
                  'Riau' : 'RIAU',
                  'Jambi' : 'JAMBI',
                  'Sumsel' :  'SUMATERA SELATAN',
                  'Bengkulu' :  'BENGKULU',
                  'Lampung' :  'LAMPUNG',
                  'Banten' :  'BANTEN',
                  'DKI' :  'DKI JAKARTA',
                  'Jabar' :  'JAWA BARAT',
                  'Jateng' : 'JAWA TENGAH',
                  'DIY' :  'DI YOGYAKARTA',
                  'Jatim' : 'JAWA TIMUR',
                  'Kalbar' : 'KALIMANTAN BARAT',
                  'Kalsel' : 'KALIMANTAN SELATAN',
                  'Kalteng' : 'KALIMANTAN TENGAH',
                  'Kaltim' : 'KALIMANTAN TIMUR',
                  'Kaltara' : 'KALIMANTAN UTARA',
                  'Sulbar'  : 'SULAWESI BARAT',
                  'Sulsel'  :  'SULAWESI SELATAN',
                  'Sulteng'  :  'SULAWESI TENGAH',
                  'Sultra'  : 'SULAWESI TENGGARA',
                  'Sulut'  :   'SULAWESI UTARA',
                  'Gorontalo'  : 'GORONTALO',
                  'Papua'  : 'PAPUA',
                  'Papbar'  : 'PAPUA BARAT',
                  'Papsel'  : 'PAPUA SELATAN',
                  'Papteng'  :'PAPUA TENGAH',
                  'Papgun'  : 'PAPUA PEGUNUNGAN',
                  'Papbarda'  : 'PAPUA BARAT DAYA',
                  
            }