# Parameter for features 
poly_kecamatan = {'NTT' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_NTT',
                  'NTB' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_NTB',
                  'Bali' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Bali' ,
                  'Malut' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Malut',
                  'Maluku' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Maluku',
                  'Kepri': r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Kepri',
                  'Babel' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Babel',
                  'NAD' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Aceh',
                  'Sumut' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Sumut',
                  'Sumbar' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Sumbar',
                  'Riau' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Riau',
                  'Jambi' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Jambi',
                  'Sumsel' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Sumsel',
                  'Bengkulu' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Bengkulu',
                  'Lampung' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Lampung',
                  'Banten' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Banten',
                  'DKI' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Jakarta',
                  'Jabar' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Jabar',
                  'Jateng' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Jateng',
                  'DIY' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Yogyakarta',
                  'Jatim' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Jatim',
                  'Kalbar' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Kalbar',
                  'Kalsel' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Kalsel',
                  'Kalteng' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Kalteng',
                  'Kaltim' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Kaltim',
                  'Kaltara' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Kaltara',
                  'Sulbar'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Sulbar',
                  'Sulsel'  :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Sulsel',
                  'Sulteng'  :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Sulteng',
                  'Sultra'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Sultra',
                  'Sulut'  :   r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Sulut',
                  'Gorontalo'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Gorontalo',
                  'Papua'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Papua',
                  'Papbar'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Papbar',
                  'Papsel'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Papsel',
                  'Papteng'  :r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Papteng',
                  'Papgun'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Papgun',
                  'Papbarda'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\KEC_Papbarda'
                  
            }