# Parameter for features 
prov_sde = {'NTT' : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_ntt',
                  'NTB' : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_ntb',
                  'Bali' : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_bali' ,
                  'Malut' : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_malut',
                  'Maluku' : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_maluku',
                  'Kepri': r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_kepri',
                  'Babel' : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_babel',
                  'NAD' : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_nad',
                  'Sumut' : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_sumut',
                  'Sumbar' : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_sumbar',
                  'Riau' : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_riau',
                  'Jambi' : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_jambi',
                  'Sumsel' :  r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_sumsel',
                  'Bengkulu' :  r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_bengkulu',
                  'Lampung' :  r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_lampung',
                  'Banten' :  r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_banten',
                  'DKI' :  r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_dki',
                  'Jabar' :  r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_jabar',
                  'Jateng' : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_jateng',
                  'DIY' :  r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_diy',
                  'Jatim' : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_jatim',
                  'Kalbar' : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_kalbar',
                  'Kalsel' : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_kalsel',
                  'Kalteng' : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_kalteng',
                  'Kaltim' : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_kaltim',
                  'Kaltara' : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_kaltara',
                  'Sulbar'  : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_sulbar',
                  'Sulsel'  :  r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_sulsel',
                  'Sulteng'  :  r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_sulteng',
                  'Sultra'  : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_sultra',
                  'Sulut'  :   r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_sulut',
                  'Gorontalo'  : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_gorontalo',
                  'Papua'  : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_papua',
                  'Papbar'  : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_papbar',
                  'Papsel'  : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_papsel',
                  'Papteng'  :r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_papteng',
                  'Papgun'  : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_papgun',
                  'Papbarda'  : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_papbarda',
                  'Indonesia' : r'F:\ASSET\spatial\BMKG_PinterIklim\PostgreSQL-gisdbiklim-geodb_bmkg(sde).sde\geodb_bmkg.sde.summary_indonesia'
                  
            }