#  Parameter for interpolation
pulau_feature = {'NTT' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Pulau_NTT',
                  'NTB' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Pulau_NTB',
                  'Bali' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Pulau_Bali' ,
                  'Malut' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Pulau_Maluku_Utara',
                  'Maluku' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Pulau_Maluku',
                  'Kepri': r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Pulau_KepRiau',
                  'Babel' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Pulau_Bangka_Belitung',
                  'Sumatera' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Pulau_Sumatera',
                  'NAD' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\NAD',
                  'Sumut' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Sumut',
                  'Sumbar' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Sumbar',
                  'Riau' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Riau',
                  'Jambi' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Jambi',
                  'Sumsel' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Sumsel',
                  'Bengkulu' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Bengkulu',
                  'Lampung' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Lampung',
                  'Jawa' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Pulau_Jawa',
                  'Banten' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Banten',
                  'DKI' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\DKI',
                  'Jabar' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Jabar',
                  'Jateng' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Jateng',
                  'DIY' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\DIY',
                  'Jatim' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Jatim',
                  'Kalimantan' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Pulau_Kalimantan',
                  'Kalbar' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Kalbar',
                  'Kalsel' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Kalsel',
                  'Kalteng' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Kalteng',
                  'Kaltim' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Kaltim',
                  'Kaltara' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Kaltara',
                  'Sulawesi'  :   r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Pulau_Sulawesi',
                  'Sulbar'  :   r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Sulbar',
                  'Sulsel'  :   r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Sulsel',
                  'Sulteng'  :   r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Sulteng',
                  'Sultra'  :   r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Sultra',
                  'Sulut'  :   r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Sulut',
                  'Gorontalo'  :   r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Gorontalo',
                  'Pulau_Papua'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Pulau_Papua',
                  'Papua'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Papua',
                  'Papbar'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Papbar',
                  'Papsel'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Papsel',
                  'Papteng'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Papteng',
                  'Papgun'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Papgun',
                  'Papbarda'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Papbarda',
                  }