# Parameter untuk referensi grid
titik_grid = {'NTT' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_NTT',
                  'NTB' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_NTB',
                  'Bali' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Bali' ,
                  'Malut' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Malut',
                  'Maluku' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Maluku',
                  'Kepri': r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Kepri',
                  'Babel' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Babel',
                  'NAD' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_NAD',
                  'Sumut' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Sumut',
                  'Sumbar' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Sumbar',
                  'Riau' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Riau',
                  'Jambi' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Jambi',
                  'Sumsel' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Sumsel',
                  'Bengkulu' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Bengkulu',
                  'Lampung' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Lampung',
                  'Banten' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Banten',
                  'DKI' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_DKI',
                  'Jabar' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Jabar',
                  'Jateng' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Jateng',
                  'DIY' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_DIY',
                  'Jatim' :  r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Jatim',
                  'Kalbar' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Kalbar',
                  'Kalsel' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Kalsel',
                  'Kalteng' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Kalteng',
                  'Kaltim' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Kaltim',
                  'Kaltara' : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Kaltara',
                  'Sulbar'  :   r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Sulbar',
                  'Sulsel'  :   r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Sulsel',
                  'Sulteng'  :   r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Sulteng',
                  'Sultra'  :   r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Sultra',
                  'Sulut'  :   r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Sulut',
                  'Gorontalo'  :   r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Gorontalo',
                  'Papua'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Papua',
                  'Papbar'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Papbar',
                  'Papsel'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Papsel',
                  'Papteng'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Papteng',
                  'Papgun'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Papgun',
                  'Papbarda'  : r'F:\ASSET\spatial\BMKG_PinterIklim\proses1_data_input.gdb\Titik_Grid_Papbarda',
                  }